import type { SiteManifest } from "@documentee/core";

export function renderSkillMd(manifest: SiteManifest): string {
  return [
    `# ${manifest.config.site.name} Agent Skill`,
    "",
    "Use this skill when an AI coding agent needs to understand, search, or update this documentation project.",
    "",
    "## Project Overview",
    "",
    manifest.config.site.description || `${manifest.config.site.name} documentation generated by Documentee.`,
    "",
    "## Reading Order",
    "",
    "1. Read repository instructions such as `AGENTS.md` when they exist.",
    "2. Read the routes listed in Important Routes before editing related content.",
    "3. Use `llms.json` for structured route and chunk lookup.",
    "4. Use `llms-full.txt` when full prose context is required.",
    "5. Use the generated MCP server when local tool-based search is available.",
    "",
    "## Important Routes",
    "",
    ...importantRoutes(manifest),
    "",
    "## CLI Verification Commands",
    "",
    "Run focused checks while editing, then the full gate before claiming completion:",
    "",
    "```bash",
    "pnpm test",
    "pnpm typecheck",
    "pnpm build",
    "pnpm docs:validate",
    "pnpm validate",
    "pnpm docs:build",
    "rm -rf dist-example && pnpm example:build",
    "```",
    "",
    "## Content Contribution Rules",
    "",
    "- Update the public docs and README when user-facing behavior changes.",
    "- Update CLI reference docs when command behavior changes.",
    "- Update config reference docs when config fields change.",
    "- Keep internal or private pages excluded from generated public routes and AI outputs.",
    "- Preserve static-first output and avoid client JavaScript unless a feature explicitly opts in.",
    "- Keep OpenAPI fixture coverage current when API reference behavior changes.",
    "",
  ].join("\n");
}

function importantRoutes(manifest: SiteManifest): string[] {
  const pageRoutes = manifest.routes
    .filter((route) => route.kind === "page")
    .map((route) => `- ${route.title}: \`${route.route}\`${route.sourceProjectPath ? ` (${route.sourceProjectPath})` : ""}`);

  const apiRoutes = manifest.operations.map((operation) => `- ${operation.method} ${operation.path}: \`${operation.route}\``);

  const routes = [...pageRoutes, ...apiRoutes].slice(0, 30);
  return routes.length > 0 ? routes : ["- No public routes were generated."];
}
