import { mkdir, rm, writeFile } from "node:fs/promises";
import { homedir } from "node:os";
import { isAbsolute, join, parse, relative, resolve } from "node:path";
import { buildManifest, loadConfig } from "@documentee/core";
import { renderLlmsJson } from "@documentee/llms";

export async function generateMcpCommand(projectRoot: string, outDir: string): Promise<void> {
  const resolvedProjectRoot = resolve(projectRoot);
  const resolvedOutDir = resolve(outDir);
  assertSafeGeneratedDirectory(resolvedProjectRoot, resolvedOutDir);

  const config = await loadConfig(resolvedProjectRoot);
  const manifest = await buildManifest(resolvedProjectRoot, config);
  const llmsJson = renderLlmsJson(manifest);

  await rm(resolvedOutDir, { recursive: true, force: true });
  await mkdir(resolvedOutDir, { recursive: true });
  await writeFile(join(resolvedOutDir, "package.json"), renderPackageJson());
  await writeFile(join(resolvedOutDir, "server.mjs"), renderServer());
  await writeFile(join(resolvedOutDir, "llms.json"), llmsJson);
  await writeFile(join(resolvedOutDir, "README.md"), renderReadme(manifest.config.site.name));
}

function renderPackageJson(): string {
  return `${JSON.stringify(
    {
      name: "documentee-mcp-server",
      version: "0.1.0",
      private: true,
      type: "module",
      scripts: {
        start: "node server.mjs",
      },
      dependencies: {
        "@modelcontextprotocol/sdk": "^1.0.0",
        zod: "^3.23.8",
      },
    },
    null,
    2,
  )}\n`;
}

function renderReadme(siteName: string): string {
  return `# ${siteName} MCP Server

This folder was generated by Documentee. It exposes a local, read-only MCP server over stdio using the generated \`llms.json\` document index.

## Run

\`\`\`bash
pnpm install
pnpm start
\`\`\`

## Tools

- \`search_docs(query)\`: Search guide chunks and API operation chunks.
- \`read_doc(route)\`: Read one documentation route by route path.
- \`list_api_operations()\`: List API operations with method, path, route, tags, and auth metadata.
- \`read_api_operation(method, path)\`: Read one API operation by method and path.

All tools are read-only and use only the local \`llms.json\` file.
`;
}

function renderServer(): string {
  return `import { readFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import { StdioServerTransport } from "@modelcontextprotocol/sdk/server/stdio.js";
import { z } from "zod";

const rootDir = dirname(fileURLToPath(import.meta.url));
const documentIndex = JSON.parse(readFileSync(join(rootDir, "llms.json"), "utf8"));

const server = new McpServer({
  name: "documentee-mcp-server",
  version: "0.1.0",
});

server.registerTool(
  "search_docs",
  {
    title: "Search Documentee Docs",
    description: "Search local documentation chunks and API operation chunks generated by Documentee. This tool only reads llms.json.",
    inputSchema: {
      query: z.string().min(1).max(200).describe("Search query to match against titles, descriptions, chunks, routes, methods, paths, and tags."),
      limit: z.number().int().min(1).max(25).default(10).describe("Maximum number of results to return."),
    },
    annotations: {
      readOnlyHint: true,
      destructiveHint: false,
      idempotentHint: true,
      openWorldHint: false,
    },
  },
  async ({ query, limit = 10 }) => {
    const results = searchDocs(query, limit);
    return {
      content: [{ type: "text", text: formatSearchResults(query, results) }],
      structuredContent: { query, count: results.length, results },
    };
  },
);

server.registerTool(
  "read_doc",
  {
    title: "Read Documentee Route",
    description: "Read one local documentation route from the generated Documentee llms.json index.",
    inputSchema: {
      route: z.string().min(1).describe("Route path to read, for example '/' or '/api-reference/config/'."),
    },
    annotations: {
      readOnlyHint: true,
      destructiveHint: false,
      idempotentHint: true,
      openWorldHint: false,
    },
  },
  async ({ route }) => {
    const doc = findRoute(route);
    if (!doc) return toolError(\`No documentation route found for '\${route}'. Use search_docs to discover valid routes.\`);
    return {
      content: [{ type: "text", text: formatRoute(doc) }],
      structuredContent: doc,
    };
  },
);

server.registerTool(
  "list_api_operations",
  {
    title: "List Documentee API Operations",
    description: "List API operations in the generated Documentee docs index.",
    inputSchema: {},
    annotations: {
      readOnlyHint: true,
      destructiveHint: false,
      idempotentHint: true,
      openWorldHint: false,
    },
  },
  async () => {
    const operations = apiOperations();
    return {
      content: [{ type: "text", text: formatOperations(operations) }],
      structuredContent: { count: operations.length, operations },
    };
  },
);

server.registerTool(
  "read_api_operation",
  {
    title: "Read Documentee API Operation",
    description: "Read one API operation by method and path from the generated Documentee docs index.",
    inputSchema: {
      method: z.string().min(1).describe("HTTP method such as GET, POST, PATCH, PUT, or DELETE."),
      path: z.string().min(1).describe("OpenAPI path, for example /messages/{id}."),
    },
    annotations: {
      readOnlyHint: true,
      destructiveHint: false,
      idempotentHint: true,
      openWorldHint: false,
    },
  },
  async ({ method, path }) => {
    const operation = apiOperations().find((route) => route.api.method.toLowerCase() === method.toLowerCase() && route.api.path === path);
    if (!operation) return toolError(\`No API operation found for \${method.toUpperCase()} \${path}. Use list_api_operations first.\`);
    return {
      content: [{ type: "text", text: formatApiOperation(operation) }],
      structuredContent: operation,
    };
  },
);

await server.connect(new StdioServerTransport());

function searchDocs(query, limit) {
  const terms = query.toLowerCase().split(/\\s+/).filter(Boolean);
  return documentIndex.routes
    .map((route) => ({ route, score: scoreRoute(route, terms) }))
    .filter((result) => result.score > 0)
    .sort((a, b) => b.score - a.score || a.route.route.localeCompare(b.route.route))
    .slice(0, limit)
    .map(({ route, score }) => ({
      route: route.route,
      title: route.title,
      description: route.description,
      contentType: route.contentType,
      score,
      matches: route.chunks.slice(0, 3).map((chunk) => ({
        headingPath: chunk.headingPath,
        text: chunk.text.slice(0, 500),
      })),
      ...(route.api ? { api: route.api } : {}),
    }));
}

function scoreRoute(route, terms) {
  const haystack = [
    route.route,
    route.title,
    route.description,
    route.api?.method,
    route.api?.path,
    ...(route.api?.tags ?? []),
    ...route.chunks.flatMap((chunk) => [chunk.text, ...chunk.headingPath]),
  ].filter(Boolean).join(" ").toLowerCase();
  return terms.reduce((score, term) => score + countOccurrences(haystack, term), 0);
}

function countOccurrences(value, term) {
  let count = 0;
  let index = value.indexOf(term);
  while (index !== -1) {
    count += 1;
    index = value.indexOf(term, index + term.length);
  }
  return count;
}

function findRoute(route) {
  const normalized = normalizeRoute(route);
  return documentIndex.routes.find((entry) => normalizeRoute(entry.route) === normalized);
}

function normalizeRoute(route) {
  if (route === "/") return "/";
  return route.endsWith("/") ? route.slice(0, -1) : route;
}

function apiOperations() {
  return documentIndex.routes
    .filter((route) => route.contentType === "api-operation" && route.api)
    .map((route) => ({
      route: route.route,
      title: route.title,
      description: route.description,
      api: route.api,
      chunks: route.chunks,
    }))
    .sort((a, b) => a.api.path.localeCompare(b.api.path) || a.api.method.localeCompare(b.api.method));
}

function formatSearchResults(query, results) {
  if (results.length === 0) return \`No docs matched '\${query}'. Try a broader term or list API operations.\`;
  return [
    \`# Search results for '\${query}'\`,
    "",
    ...results.map((result) => [
      \`## \${result.title}\`,
      \`- Route: \${result.route}\`,
      \`- Type: \${result.contentType}\`,
      result.description ? \`- Description: \${result.description}\` : undefined,
      result.api ? \`- Operation: \${result.api.method} \${result.api.path}\` : undefined,
      result.matches[0] ? \`- Match: \${result.matches[0].text}\` : undefined,
      "",
    ].filter(Boolean).join("\\n")),
  ].join("\\n");
}

function formatRoute(route) {
  return [
    \`# \${route.title}\`,
    "",
    route.description,
    "",
    \`Route: \${route.route}\`,
    route.source ? \`Source: \${route.source}\` : undefined,
    "",
    ...route.chunks.map((chunk) => [
      \`## \${chunk.headingPath.join(" > ")}\`,
      "",
      chunk.text,
      "",
    ].join("\\n")),
  ].filter(Boolean).join("\\n");
}

function formatOperations(operations) {
  if (operations.length === 0) return "No API operations were found in this docs index.";
  return [
    "# API Operations",
    "",
    ...operations.map((operation) => [
      \`- \${operation.api.method} \${operation.api.path}\`,
      \`  - Route: \${operation.route}\`,
      operation.api.tags.length ? \`  - Tags: \${operation.api.tags.join(", ")}\` : undefined,
      operation.api.auth.length ? \`  - Auth: \${operation.api.auth.join(", ")}\` : undefined,
      operation.api.deprecated ? "  - Deprecated: true" : undefined,
    ].filter(Boolean).join("\\n")),
  ].join("\\n");
}

function formatApiOperation(operation) {
  return [
    \`# \${operation.api.method} \${operation.api.path}\`,
    "",
    operation.description,
    "",
    \`Route: \${operation.route}\`,
    operation.api.tags.length ? \`Tags: \${operation.api.tags.join(", ")}\` : undefined,
    operation.api.auth.length ? \`Auth: \${operation.api.auth.join(", ")}\` : undefined,
    operation.api.deprecated ? "Deprecated: true" : undefined,
    "",
    ...operation.chunks.map((chunk) => chunk.text).filter(Boolean),
  ].filter(Boolean).join("\\n");
}

function toolError(message) {
  return {
    isError: true,
    content: [{ type: "text", text: message }],
  };
}
`;
}

function assertSafeGeneratedDirectory(projectRoot: string, outDir: string): void {
  const rootDir = parse(outDir).root;
  const blocked = new Set([rootDir, homedir(), process.cwd(), projectRoot].map((path) => resolve(path)));
  const relativeProject = relative(outDir, projectRoot);
  const outDirContainsProject = relativeProject === "" || (!relativeProject.startsWith("..") && !isAbsolute(relativeProject));

  if (blocked.has(outDir) || outDirContainsProject) {
    throw new Error(`Refusing to clean unsafe MCP output directory: ${outDir}`);
  }
}
