import type { DocumenteeConfig } from "./config.js";

export type ThemeMode = "light" | "dark";
export type ThemeConfig = DocumenteeConfig["theme"];
export type ThemePresetTokens = Partial<Omit<ThemeConfig, "preset" | "designSystem" | "overrides" | "customCss" | "darkMode">>;
export type ThemePreset = ThemePresetTokens & {
  dark?: ThemePresetTokens;
};

const defaultMethodColors = {
  methodGetColor: "#2563eb",
  methodPostColor: "#16a34a",
  methodPutColor: "#d97706",
  methodPatchColor: "#d97706",
  methodDeleteColor: "#dc2626",
  methodOptionsColor: "#7c3aed",
  methodHeadColor: "#64748b",
  methodTraceColor: "#7c3aed",
} satisfies ThemePresetTokens;

export const themePresets: Record<NonNullable<ThemeConfig["preset"]>, ThemePreset> = {
  neutral: {
    primaryColor: "#18181b",
    accentColor: "#52525b",
    backgroundColor: "#ffffff",
    textColor: "#18181b",
    mutedTextColor: "#71717a",
    borderColor: "#d4d4d8",
    codeBackgroundColor: "#f4f4f5",
    dark: {
      backgroundColor: "#111113",
      textColor: "#f4f4f5",
      mutedTextColor: "#a1a1aa",
      borderColor: "#3f3f46",
      codeBackgroundColor: "#18181b",
    },
  },
  mint: {
    primaryColor: "#0f766e",
    accentColor: "#14b8a6",
    backgroundColor: "#f8fffc",
    textColor: "#10201c",
    mutedTextColor: "#4b635d",
    borderColor: "#b7d8ce",
    codeBackgroundColor: "#ecfdf5",
    dark: {
      primaryColor: "#5eead4",
      accentColor: "#2dd4bf",
      backgroundColor: "#061f1a",
      textColor: "#eafff8",
      mutedTextColor: "#9fd6ca",
      borderColor: "#1f4d43",
      codeBackgroundColor: "#082f29",
    },
  },
  slate: {
    primaryColor: "#334155",
    accentColor: "#2563eb",
    backgroundColor: "#f8fafc",
    textColor: "#0f172a",
    mutedTextColor: "#64748b",
    borderColor: "#cbd5e1",
    codeBackgroundColor: "#f1f5f9",
    dark: {
      primaryColor: "#93c5fd",
      accentColor: "#38bdf8",
      backgroundColor: "#0f172a",
      textColor: "#f8fafc",
      mutedTextColor: "#cbd5e1",
      borderColor: "#334155",
      codeBackgroundColor: "#111827",
    },
  },
  highContrast: {
    primaryColor: "#000000",
    accentColor: "#1d4ed8",
    backgroundColor: "#ffffff",
    textColor: "#000000",
    mutedTextColor: "#1f2937",
    borderColor: "#000000",
    codeBackgroundColor: "#f3f4f6",
    dark: {
      primaryColor: "#ffffff",
      accentColor: "#facc15",
      backgroundColor: "#000000",
      textColor: "#ffffff",
      mutedTextColor: "#f5f5f5",
      borderColor: "#ffffff",
      codeBackgroundColor: "#111111",
    },
  },
  classic: {
    primaryColor: "#7f1d1d",
    accentColor: "#1f4f46",
    backgroundColor: "#fffdfa",
    textColor: "#251714",
    mutedTextColor: "#6b5b55",
    borderColor: "#d8c7b8",
    codeBackgroundColor: "#f6f0e8",
    fontFamily: "Georgia, ui-serif, serif",
    dark: {
      primaryColor: "#fca5a5",
      accentColor: "#7dd3c7",
      backgroundColor: "#211916",
      textColor: "#fff7ed",
      mutedTextColor: "#d8c7b8",
      borderColor: "#6b5046",
      codeBackgroundColor: "#2b211d",
    },
  },
  terminal: {
    primaryColor: "#047857",
    accentColor: "#ca8a04",
    backgroundColor: "#fbfdf8",
    textColor: "#101510",
    mutedTextColor: "#4b604f",
    borderColor: "#b9d8bf",
    codeBackgroundColor: "#eef8ee",
    fontFamily: "IBM Plex Mono, ui-monospace, SFMono-Regular, Menlo, Consolas, monospace",
    dark: {
      primaryColor: "#34d399",
      accentColor: "#fbbf24",
      backgroundColor: "#050806",
      textColor: "#d1fae5",
      mutedTextColor: "#86efac",
      borderColor: "#14532d",
      codeBackgroundColor: "#07120b",
    },
  },
  startup: {
    primaryColor: "#c81046",
    accentColor: "#2563eb",
    backgroundColor: "#fff8f7",
    textColor: "#27121a",
    mutedTextColor: "#75505e",
    borderColor: "#f5c4ce",
    codeBackgroundColor: "#fff1f2",
    dark: {
      primaryColor: "#fb7185",
      accentColor: "#93c5fd",
      backgroundColor: "#1f1020",
      textColor: "#fff1f5",
      mutedTextColor: "#f0a9bd",
      borderColor: "#5b2744",
      codeBackgroundColor: "#2a1429",
    },
  },
  enterprise: {
    primaryColor: "#1d4ed8",
    accentColor: "#0f766e",
    backgroundColor: "#f7fbff",
    textColor: "#0c1a2e",
    mutedTextColor: "#4b647f",
    borderColor: "#bfd3ea",
    codeBackgroundColor: "#edf4ff",
    dark: {
      primaryColor: "#60a5fa",
      accentColor: "#5eead4",
      backgroundColor: "#081424",
      textColor: "#eff6ff",
      mutedTextColor: "#b7cbe2",
      borderColor: "#29415f",
      codeBackgroundColor: "#0c1b2e",
    },
  },
  api: {
    primaryColor: "#0e7490",
    accentColor: "#7c3aed",
    backgroundColor: "#f7fdff",
    textColor: "#0b1b22",
    mutedTextColor: "#4b626b",
    borderColor: "#b8dbe5",
    codeBackgroundColor: "#ecfeff",
    dark: {
      primaryColor: "#67e8f9",
      accentColor: "#c4b5fd",
      backgroundColor: "#061923",
      textColor: "#ecfeff",
      mutedTextColor: "#a5d8e6",
      borderColor: "#164e63",
      codeBackgroundColor: "#082532",
    },
  },
  minimal: {
    primaryColor: "#111827",
    accentColor: "#6b7280",
    backgroundColor: "#ffffff",
    textColor: "#111827",
    mutedTextColor: "#6b7280",
    borderColor: "#e5e7eb",
    codeBackgroundColor: "#f9fafb",
    radius: "4px",
    dark: {
      primaryColor: "#fafafa",
      accentColor: "#a3a3a3",
      backgroundColor: "#0a0a0a",
      textColor: "#fafafa",
      mutedTextColor: "#a3a3a3",
      borderColor: "#2a2a2a",
      codeBackgroundColor: "#141414",
    },
  },
};

export const designSystemPresets: Record<NonNullable<ThemeConfig["designSystem"]>, ThemePreset> = {
  "minimal-technical": {
    ...defaultMethodColors,
    primaryColor: "#2563eb",
    accentColor: "#1d4ed8",
    backgroundColor: "#ffffff",
    textColor: "#111827",
    mutedTextColor: "#6b7280",
    borderColor: "#d1d5db",
    codeBackgroundColor: "#f5f5f5",
    fontFamily: "Inter, system-ui, sans-serif",
    codeFontFamily: "JetBrains Mono, ui-monospace, SFMono-Regular, Menlo, Consolas, monospace",
    radius: "10px",
    navWidth: "280px",
    contentWidth: "860px",
    contentPadding: "clamp(24px, 4vw, 44px)",
    densitySpace: "14px",
    cardRadius: "8px",
    bodyFontSize: "16px",
    smallFontSize: "14px",
    h1Size: "clamp(36px, 4vw, 52px)",
    h2Size: "clamp(24px, 2.2vw, 30px)",
    lineHeight: "1.72",
    headingWeight: "750",
    shadowCard: "0 10px 30px rgb(15 23 42 / 5%)",
    shadowRaised: "0 1px 2px rgb(15 23 42 / 8%)",
    dark: {
      primaryColor: "#93c5fd",
      accentColor: "#bfdbfe",
      backgroundColor: "#111827",
      textColor: "#f9fafb",
      mutedTextColor: "#d1d5db",
      borderColor: "#374151",
      codeBackgroundColor: "#1f2937",
      shadowCard: "0 18px 48px rgb(0 0 0 / 18%)",
      shadowRaised: "0 8px 20px rgb(0 0 0 / 22%)",
    },
  },
  "modern-glass": {
    ...defaultMethodColors,
    primaryColor: "#5b8cff",
    accentColor: "#7c3aed",
    backgroundColor: "#09090b",
    textColor: "#fafafa",
    mutedTextColor: "#a1a1aa",
    borderColor: "rgba(255,255,255,.08)",
    codeBackgroundColor: "#18181b",
    fontFamily: "Geist Sans, Inter, ui-sans-serif, system-ui, sans-serif",
    codeFontFamily: "Geist Mono, ui-monospace, SFMono-Regular, Menlo, Consolas, monospace",
    radius: "14px",
    navWidth: "300px",
    contentWidth: "960px",
    contentPadding: "clamp(24px, 4vw, 48px)",
    densitySpace: "12px",
    cardRadius: "14px",
    pageBackground: "radial-gradient(circle at top left, color-mix(in srgb, #5b8cff 20%, transparent), transparent 34%), #09090b",
    sidebarBackgroundColor: "rgba(17,17,19,.74)",
    panelBackgroundColor: "rgba(24,24,27,.72)",
    heroBackground: "linear-gradient(135deg, rgba(91,140,255,.18), rgba(124,58,237,.14))",
    bodyFontSize: "16px",
    smallFontSize: "14px",
    h1Size: "clamp(40px, 4.6vw, 60px)",
    h2Size: "clamp(26px, 2.5vw, 34px)",
    lineHeight: "1.7",
    headingWeight: "760",
    shadowCard: "0 24px 80px rgb(0 0 0 / 32%)",
    shadowRaised: "0 20px 60px rgb(0 0 0 / 34%)",
    dark: {
      primaryColor: "#5b8cff",
      accentColor: "#7c3aed",
      backgroundColor: "#09090b",
      textColor: "#fafafa",
      mutedTextColor: "#a1a1aa",
      borderColor: "rgba(255,255,255,.08)",
      codeBackgroundColor: "#18181b",
    },
  },
  "api-ide": {
    ...defaultMethodColors,
    primaryColor: "#3b82f6",
    accentColor: "#8b5cf6",
    backgroundColor: "#0b0d12",
    textColor: "#f3f4f6",
    mutedTextColor: "#94a3b8",
    borderColor: "#364152",
    codeBackgroundColor: "#171c26",
    fontFamily: "Geist Sans, Inter, ui-sans-serif, system-ui, sans-serif",
    codeFontFamily: "JetBrains Mono, ui-monospace, SFMono-Regular, Menlo, Consolas, monospace",
    radius: "8px",
    navWidth: "280px",
    contentWidth: "980px",
    contentPadding: "clamp(18px, 3vw, 32px)",
    densitySpace: "10px",
    cardRadius: "8px",
    sidebarBackgroundColor: "#0f131a",
    panelBackgroundColor: "#171c26",
    heroBackground: "linear-gradient(135deg, rgba(59,130,246,.18), rgba(139,92,246,.12))",
    bodyFontSize: "15px",
    smallFontSize: "13px",
    h1Size: "clamp(34px, 4vw, 48px)",
    h2Size: "clamp(22px, 2.2vw, 28px)",
    lineHeight: "1.64",
    headingWeight: "720",
    shadowCard: "0 14px 42px rgb(0 0 0 / 28%)",
    shadowRaised: "0 10px 30px rgb(0 0 0 / 24%)",
    methodGetColor: "#22c55e",
    methodPostColor: "#3b82f6",
    methodPutColor: "#f59e0b",
    methodPatchColor: "#8b5cf6",
    methodDeleteColor: "#ef4444",
    methodOptionsColor: "#06b6d4",
    methodHeadColor: "#64748b",
    methodTraceColor: "#06b6d4",
    dark: {
      primaryColor: "#3b82f6",
      accentColor: "#8b5cf6",
      backgroundColor: "#0b0d12",
      textColor: "#f3f4f6",
      mutedTextColor: "#94a3b8",
      borderColor: "#364152",
      codeBackgroundColor: "#171c26",
    },
  },
  "enterprise-knowledge": {
    ...defaultMethodColors,
    primaryColor: "#2563eb",
    accentColor: "#8b5cf6",
    backgroundColor: "#f8fafc",
    textColor: "#0f172a",
    mutedTextColor: "#64748b",
    borderColor: "#cbd5e1",
    codeBackgroundColor: "#f1f5f9",
    fontFamily: "IBM Plex Sans, Inter, ui-sans-serif, system-ui, sans-serif",
    codeFontFamily: "IBM Plex Mono, ui-monospace, SFMono-Regular, Menlo, Consolas, monospace",
    radius: "10px",
    navWidth: "320px",
    contentWidth: "960px",
    contentPadding: "clamp(24px, 4vw, 44px)",
    densitySpace: "14px",
    cardRadius: "10px",
    sidebarBackgroundColor: "#f1f5f9",
    panelBackgroundColor: "#ffffff",
    bodyFontSize: "16px",
    smallFontSize: "14px",
    h1Size: "clamp(38px, 4.2vw, 56px)",
    h2Size: "clamp(26px, 2.4vw, 34px)",
    lineHeight: "1.72",
    headingWeight: "760",
    shadowCard: "0 14px 36px rgb(15 23 42 / 8%)",
    shadowRaised: "0 8px 24px rgb(15 23 42 / 10%)",
    dark: {
      primaryColor: "#60a5fa",
      accentColor: "#c4b5fd",
      backgroundColor: "#0f172a",
      textColor: "#f8fafc",
      mutedTextColor: "#cbd5e1",
      borderColor: "#334155",
      codeBackgroundColor: "#111827",
      sidebarBackgroundColor: "#111827",
      panelBackgroundColor: "#111827",
      heroBackground: "linear-gradient(135deg, rgba(96,165,250,.18), rgba(196,181,253,.12))",
    },
  },
  "premium-editorial": {
    ...defaultMethodColors,
    primaryColor: "#4f46e5",
    accentColor: "#ec4899",
    backgroundColor: "#fcfcfd",
    textColor: "#111827",
    mutedTextColor: "#6b7280",
    borderColor: "#e5e7eb",
    codeBackgroundColor: "#f7f7f8",
    fontFamily: "Instrument Serif, Georgia, serif",
    codeFontFamily: "JetBrains Mono, ui-monospace, SFMono-Regular, Menlo, Consolas, monospace",
    radius: "20px",
    navWidth: "260px",
    contentWidth: "760px",
    contentPadding: "clamp(32px, 6vw, 72px)",
    densitySpace: "20px",
    cardRadius: "20px",
    panelBackgroundColor: "#ffffff",
    heroBackground: "linear-gradient(135deg, rgba(79,70,229,.12), rgba(236,72,153,.10))",
    bodyFontSize: "18px",
    smallFontSize: "15px",
    h1Size: "clamp(48px, 6vw, 72px)",
    h2Size: "clamp(30px, 3vw, 40px)",
    lineHeight: "1.78",
    headingWeight: "650",
    shadowCard: "0 30px 80px rgb(17 24 39 / 8%)",
    shadowRaised: "0 18px 50px rgb(17 24 39 / 10%)",
    dark: {
      primaryColor: "#818cf8",
      accentColor: "#f472b6",
      backgroundColor: "#09090b",
      textColor: "#fafafa",
      mutedTextColor: "#a1a1aa",
      borderColor: "#27272a",
      codeBackgroundColor: "#1b1b1f",
      sidebarBackgroundColor: "#121214",
      panelBackgroundColor: "#121214",
      heroBackground: "linear-gradient(135deg, rgba(129,140,248,.16), rgba(244,114,182,.12))",
    },
  },
  "sci-fi-console": {
    ...defaultMethodColors,
    primaryColor: "#5ea1ff",
    accentColor: "#8b5cf6",
    backgroundColor: "#050608",
    textColor: "#f8fafc",
    mutedTextColor: "#94a3b8",
    borderColor: "#263244",
    codeBackgroundColor: "#141926",
    fontFamily: "Geist Sans, Inter, ui-sans-serif, system-ui, sans-serif",
    codeFontFamily: "Berkeley Mono, JetBrains Mono, ui-monospace, SFMono-Regular, Menlo, Consolas, monospace",
    radius: "12px",
    navWidth: "300px",
    contentWidth: "980px",
    contentPadding: "clamp(20px, 4vw, 40px)",
    densitySpace: "12px",
    cardRadius: "12px",
    pageBackground: "radial-gradient(circle at top right, color-mix(in srgb, #22d3ee 14%, transparent), transparent 30%), #050608",
    sidebarBackgroundColor: "#0f131c",
    panelBackgroundColor: "#141926",
    heroBackground: "linear-gradient(135deg, rgba(94,161,255,.18), rgba(34,211,238,.10))",
    bodyFontSize: "16px",
    smallFontSize: "14px",
    h1Size: "clamp(40px, 4.8vw, 58px)",
    h2Size: "clamp(26px, 2.6vw, 34px)",
    lineHeight: "1.68",
    headingWeight: "760",
    shadowCard: "0 22px 70px rgb(34 211 238 / 10%)",
    shadowRaised: "0 16px 44px rgb(94 161 255 / 13%)",
    methodGetColor: "#22c55e",
    methodPostColor: "#5ea1ff",
    methodPutColor: "#f59e0b",
    methodPatchColor: "#8b5cf6",
    methodDeleteColor: "#ef4444",
    methodOptionsColor: "#22d3ee",
    methodHeadColor: "#64748b",
    methodTraceColor: "#22d3ee",
    dark: {
      primaryColor: "#5ea1ff",
      accentColor: "#8b5cf6",
      backgroundColor: "#050608",
      textColor: "#f8fafc",
      mutedTextColor: "#94a3b8",
      borderColor: "#263244",
      codeBackgroundColor: "#141926",
    },
  },
  "api-observatory": {
    ...defaultMethodColors,
    primaryColor: "#3b82f6",
    accentColor: "#14b8a6",
    backgroundColor: "#0b0f14",
    textColor: "#f8fafc",
    mutedTextColor: "#94a3b8",
    borderColor: "#2a3342",
    codeBackgroundColor: "#1a2230",
    fontFamily: "Inter, ui-sans-serif, system-ui, sans-serif",
    codeFontFamily: "JetBrains Mono, ui-monospace, SFMono-Regular, Menlo, Consolas, monospace",
    radius: "8px",
    navWidth: "300px",
    contentWidth: "1040px",
    contentPadding: "clamp(18px, 3vw, 34px)",
    densitySpace: "10px",
    cardRadius: "8px",
    sidebarBackgroundColor: "#121821",
    panelBackgroundColor: "#1a2230",
    heroBackground: "linear-gradient(135deg, rgba(59,130,246,.16), rgba(20,184,166,.14))",
    bodyFontSize: "15px",
    smallFontSize: "13px",
    h1Size: "clamp(36px, 4.4vw, 52px)",
    h2Size: "clamp(24px, 2.3vw, 30px)",
    lineHeight: "1.64",
    headingWeight: "760",
    shadowCard: "0 18px 50px rgb(0 0 0 / 28%)",
    shadowRaised: "0 12px 36px rgb(0 0 0 / 24%)",
    methodGetColor: "#22c55e",
    methodPostColor: "#3b82f6",
    methodPutColor: "#f59e0b",
    methodPatchColor: "#8b5cf6",
    methodDeleteColor: "#ef4444",
    methodOptionsColor: "#14b8a6",
    methodHeadColor: "#94a3b8",
    methodTraceColor: "#14b8a6",
    dark: {
      primaryColor: "#3b82f6",
      accentColor: "#14b8a6",
      backgroundColor: "#0b0f14",
      textColor: "#f8fafc",
      mutedTextColor: "#94a3b8",
      borderColor: "#2a3342",
      codeBackgroundColor: "#1a2230",
    },
  },
  "knowledge-graph": {
    ...defaultMethodColors,
    primaryColor: "#2563eb",
    accentColor: "#14b8a6",
    backgroundColor: "#fafafa",
    textColor: "#111827",
    mutedTextColor: "#6b7280",
    borderColor: "#d4d4d8",
    codeBackgroundColor: "#f5f5f5",
    fontFamily: "Inter, ui-sans-serif, system-ui, sans-serif",
    codeFontFamily: "JetBrains Mono, ui-monospace, SFMono-Regular, Menlo, Consolas, monospace",
    radius: "12px",
    navWidth: "300px",
    contentWidth: "940px",
    contentPadding: "clamp(24px, 4vw, 48px)",
    densitySpace: "14px",
    cardRadius: "12px",
    sidebarBackgroundColor: "#ffffff",
    panelBackgroundColor: "#ffffff",
    heroBackground: "linear-gradient(135deg, rgba(37,99,235,.11), rgba(20,184,166,.12))",
    bodyFontSize: "16px",
    smallFontSize: "14px",
    h1Size: "clamp(38px, 4.4vw, 56px)",
    h2Size: "clamp(25px, 2.4vw, 32px)",
    lineHeight: "1.72",
    headingWeight: "740",
    shadowCard: "0 16px 44px rgb(17 24 39 / 7%)",
    shadowRaised: "0 10px 28px rgb(17 24 39 / 9%)",
    dark: {
      primaryColor: "#93c5fd",
      accentColor: "#2dd4bf",
      backgroundColor: "#09090b",
      textColor: "#fafafa",
      mutedTextColor: "#a1a1aa",
      borderColor: "#2a2a2a",
      codeBackgroundColor: "#141414",
      sidebarBackgroundColor: "#141414",
      panelBackgroundColor: "#141414",
      heroBackground: "linear-gradient(135deg, rgba(147,197,253,.14), rgba(45,212,191,.12))",
    },
  },
};

export function resolveThemeTokens(theme: ThemeConfig, mode: ThemeMode): Record<string, string> {
  const preset = theme.designSystem ? designSystemPresets[theme.designSystem] : theme.preset ? themePresets[theme.preset] : {};
  const modePreset: ThemePresetTokens = mode === "dark" ? { ...preset, ...preset.dark } : preset;
  const overrides = theme.overrides ?? {};
  const token = <Key extends keyof ThemePresetTokens>(key: Key, fallback?: string): string | undefined => {
    return overrides[key] ?? theme[key] ?? modePreset[key] ?? fallback;
  };
  const primary = token("primaryColor", "#18181b")!;
  const accent = token("accentColor", primary)!;
  const link = mode === "dark" ? preset.dark?.primaryColor ?? "#93c5fd" : primary;
  const linkHover = mode === "dark" ? preset.dark?.accentColor ?? "#bfdbfe" : primary.toLowerCase() === "#2563eb" ? "#1d4ed8" : accent;
  const background = token("backgroundColor", mode === "dark" ? "#0b1020" : "Canvas")!;
  const border = token("borderColor", mode === "dark" ? "#263244" : "#d4d4d8")!;
  const surface = token("panelBackgroundColor", background)!;
  const surfaceRaised = `color-mix(in srgb, ${surface} 96%, ${border})`;

  return {
    "--doc-primary": primary,
    "--doc-accent": accent,
    "--doc-background": background,
    "--doc-page-background": token("pageBackground", `color-mix(in srgb, ${background} 94%, ${border})`)!,
    "--doc-sidebar-background": token("sidebarBackgroundColor", `color-mix(in srgb, ${background} 94%, ${border})`)!,
    "--doc-panel-background": surface,
    "--doc-hero-background": token("heroBackground", `color-mix(in srgb, ${primary} 7%, ${background})`)!,
    "--doc-text": token("textColor", mode === "dark" ? "#f8fafc" : "CanvasText")!,
    "--doc-muted-text": token("mutedTextColor", mode === "dark" ? "#a8b3c7" : "#52525b")!,
    "--doc-border": border,
    "--doc-code-background": token("codeBackgroundColor", mode === "dark" ? "#111827" : "transparent")!,
    "--doc-font-family": token("fontFamily", "Inter, ui-sans-serif, system-ui, sans-serif")!,
    "--doc-code-font-family": token("codeFontFamily", "ui-monospace, SFMono-Regular, Menlo, Consolas, monospace")!,
    "--doc-radius": token("radius", "8px")!,
    "--doc-card-radius": token("cardRadius", "8px")!,
    "--doc-nav-width": token("navWidth", "280px")!,
    "--doc-content-width": token("contentWidth", "920px")!,
    "--doc-content-padding": token("contentPadding", "clamp(24px, 4vw, 44px)")!,
    "--doc-density-space": token("densitySpace", "14px")!,
    "--doc-body-font-size": token("bodyFontSize", "16px")!,
    "--doc-small-font-size": token("smallFontSize", "14px")!,
    "--doc-h1-size": token("h1Size", "clamp(36px, 4.8vw, 58px)")!,
    "--doc-h2-size": token("h2Size", "clamp(24px, 2.4vw, 31px)")!,
    "--doc-line-height": token("lineHeight", "1.72")!,
    "--doc-heading-weight": token("headingWeight", "750")!,
    "--doc-link": link,
    "--doc-link-hover": linkHover,
    "--doc-active-background": `color-mix(in srgb, ${link} 14%, transparent)`,
    "--doc-surface": surface,
    "--doc-surface-raised": surfaceRaised,
    "--doc-card-border": `color-mix(in srgb, ${border} 78%, transparent)`,
    "--doc-focus-ring": `color-mix(in srgb, ${link} 70%, white)`,
    "--doc-space-1": "4px",
    "--doc-space-2": "8px",
    "--doc-space-3": "12px",
    "--doc-space-4": "16px",
    "--doc-space-5": "20px",
    "--doc-space-6": "24px",
    "--doc-shadow-card": token("shadowCard", mode === "dark" ? "0 18px 48px rgb(0 0 0 / 18%)" : "0 18px 48px rgb(15 23 42 / 6%)")!,
    "--doc-shadow-raised": token("shadowRaised", mode === "dark" ? "0 16px 44px rgb(0 0 0 / 22%)" : "0 10px 28px rgb(15 23 42 / 8%)")!,
    "--doc-method-get": token("methodGetColor", mode === "dark" ? "#60a5fa" : defaultMethodColors.methodGetColor)!,
    "--doc-method-post": token("methodPostColor", defaultMethodColors.methodPostColor)!,
    "--doc-method-put": token("methodPutColor", defaultMethodColors.methodPutColor)!,
    "--doc-method-patch": token("methodPatchColor", defaultMethodColors.methodPatchColor)!,
    "--doc-method-delete": token("methodDeleteColor", defaultMethodColors.methodDeleteColor)!,
    "--doc-method-options": token("methodOptionsColor", defaultMethodColors.methodOptionsColor)!,
    "--doc-method-head": token("methodHeadColor", defaultMethodColors.methodHeadColor)!,
    "--doc-method-trace": token("methodTraceColor", defaultMethodColors.methodTraceColor)!,
    "--doc-success": mode === "dark" ? "#4ade80" : "#16a34a",
    "--doc-success-text": mode === "dark" ? "#86efac" : "#166534",
    "--doc-warning": mode === "dark" ? "#fbbf24" : "#d97706",
    "--doc-warning-text": mode === "dark" ? "#fde68a" : "#92400e",
    "--doc-danger": mode === "dark" ? "#f87171" : "#dc2626",
    "--doc-danger-text": mode === "dark" ? "#fecaca" : "#991b1b",
    "--doc-info": mode === "dark" ? "#60a5fa" : "#2563eb",
    "--doc-info-text": mode === "dark" ? "#bfdbfe" : "#1d4ed8",
  };
}

export function resolveThemeCustomCss(theme: ThemeConfig): string {
  const customCss = theme.overrides?.customCss ?? theme.customCss ?? "";
  return customCss.replace(/<\/style/gi, "<\\/style");
}
